### PR TITLE
unit tests without changing database.php

### PR DESCRIPTION
**Pull request by mrothauer**
unit tests can be run now without changing the database in database.php. first step for further automatism done :-)

### CODE REVIEW

**Comment by k-pd** [comment]
No time for testing, yet. But: in assertPageForErrors() please use English only comments.

**Comment by k-pd** [comment]
The frontend tests passed well, but there are some issues with the applied coding standards. There are assertions like in AssetCompressHelperTest::testInlineCssDevelopment() that use string literals containing TAB characters, which now must be spaces.

**Comment by k-pd** [comment]
Managed to get all tests running again, but AssertCompress requires Hogan.js for one test and I could not get that installed in a way, that AssertCompress wants to accept it.

Another more important problem remains: The CSS and JS files used by AssertCompress for unit testing are checked into Git (don't know why). So now these files are changed by PHPCBF, but the tests cannot be changed (not under Git control). What to do?

**Comment by mrothauer** [comment]
in my repo there are no css and js files frmo asset compress. where should they be found? the whole plugin folder is not in the repo.
maybe you did a composer install without --prefer-dist, then the .git folder is cloned in the folder "Plugin" and maybe messes up your repo
https://github.com/foodcoopshop/foodcoopshop/tree/develop/Plugin

i would just ignore the asset compress tests - if this plugin does not work we will know it quickly as it will break all javascript and css

thanks for reviewing!

**Comment by k-pd** [comment]
I got caught with composer not overwriting anything on doing update/install (like git does on checkout). AssetCompress uses no files from the repo for testing. I tested running phpcbf on my working tree and didn't do a complete new clone and install after that...

**Pull request merged**
