### PR TITLE
Apply automatically fixable rules from fcs-rules.xml to project

### PR DESCRIPTION
**Pull request by k-pd**
There are still many violations that cannot be fixed automatically. Most
are "Method name not CamelCaps" and "Visibility not stated".

The unfixed files are:
Fixed: /Lib/Pdf/FCS_TCPDF.php
Fixed: /View/Helper/MyHtmlHelper.php
Fixed: /View/Layouts/plain.ctp
Fixed: /View/Elements/footer.ctp
Ignored: /Config/database.default.php
Fixed: /Model/BlogPost.php
Fixed: /Plugin/Admin/View/Payments/product.ctp
Fixed: /Plugin/Admin/View/Reports/payments.ctp
Fixed: /Plugin/Admin/Controller/ListsController.php
Fixed: /Plugin/Admin/Controller/DepositsController.php
Fixed: /Plugin/Admin/Controller/PaymentsController.php
Fixed: /Plugin/EmailLog/Lib/Log/Engine/EmailLog.php
Fixed: /Controller/PagesController.php
Fixed: /Controller/CartsController.php
Fixed: /Controller/CategoriesController.php
Fixed: /Controller/Component/StringComponent.php
Fixed: /Controller/CustomersController.php

### CODE REVIEW

**Comment by k-pd** [comment]
Followup from #55, see #42 , #41 and #38

**Comment by mrothauer** [comment]
Fixed: /Lib/Pdf/FCS_TCPDF.php
Fixed: /View/Helper/MyHtmlHelper.php
Used by CakePHP - classname not changeable /Config/database.default.php
In this case it makes sense to update your first comment so that we don't interfere.

**Comment by k-pd** [comment]
Will adjust ruleset for unchangeable files using `<exclude-pattern>Config/database.default.php</exclude-pattern>`.

**Comment by mrothauer** [comment]
all done :-)

**Comment by k-pd** [comment]
Thanks for quick changes!

**Pull request merged**
