### PR TITLE
Feature/issue 41 enforce coding standards

### PR DESCRIPTION
**Pull request by k-pd**
These scripts are working on my machine. Please test on yours. When doing `composer install` or `composer update` the git hooks should be copied to .git/hooks/ and start working for your next commit / push.

There is something missing: whenever `git pull` changes composer.json (or composer.lock) you still have to start composer yourself. I found a git hook script for that, but get that running you first have to `git pull` and do `composer install`...

### CODE REVIEW

**Comment by mrothauer** [comment]
the script was copied successfully in the hooks folder, but did not do what i expected (see test commits). i just added some spaces at the end of the line.
or did i misunderstand something? working on windows 10, but windows seems to be considered in the hooks.

**Comment by mrothauer** [comment]
sorry, i was confused with the trailing whitespace issue...
what should the script do? reformatting php source code in psr2-style? this did not work (see last commits)

**Comment by k-pd** [comment]
OK, seems to work on Win10, too. That's great news...

On commit tests PHP Lint and Whitespace are done. On push test PSR-2 is run. They work like this:

PHP Lint: On errors commit fails. You must repair files, git add the changes and git commit again. Cannot be automised at all, I think.

Whitespace: The script automatically removes trailing whitespace and git adds the file if it was changed. As MarkDown uses trailing whitespace as line break sign, these files are not touched. The commit is successful and there is no notice if files were changed during commit.

This commit solution is not perfect. I want to integrate PSR-2 testing also here.

PSR-2: The script can show standards violations (default) or try to automatically solve them (change script .git/hooks/pre-push at the top). I chose showing violations, because I don't know how to git commit changed files into the running git push. I think, that cannot be done.

There are also other issues with the pre-commit / pre-push solutions: The testing is run on the working directory contents, which is not always the version you commit / push. But I'm not expert in shell scripting enough to do stuff as complex as *checkout committed files to a temp directory, run all the tests on them, add changes to the local repository (in case of push commit them and add the commit to the already running push), cleanup the temp directory and at last maybe update the working directory*.

**Comment by k-pd** [comment]
#42 #38

**Comment by k-pd** [comment]
Just found out: latest version of PSR-2 requires classes to be in a namespace (and no class of foodcoopshop is in a namespace yet). This renders pushing of class changes impossible right now.

**Comment by k-pd** [comment]
OK, another problem: All files are sent to CodeSniffer, making it complain about XML files not being correct PHP files. Need another solution for that.

**Comment by k-pd** [comment]
Added a filename filter script to solve the CodeSniffer problem. The problem is, that by using explicit filenames to start CodeSniffer it ignores all file-dependend settings. So a CSS file is parsed by *all* possible sniffs and of course some would fail, too. If more file extensions need to be checked, add them to the file filter script.

**Comment by mrothauer** [comment]
i just created a test branch and changed the app controller

class AppController extends Controller          {

i expected the spaces between Controller and the { to be reduced to 1 - did not work
https://github.com/foodcoopshop/foodcoopshop/blob/test/Controller/AppController.php

after 
  public $components = array(        
i added whitespace - also not removed

in case i did not understand - could you give me a test case that works on your machine?

**Comment by k-pd** [comment]
OK, looking for all possible failure sources. Here's my steps and results that do work as I expect them to work.

Pull the latest version of this branch and *do not switch* branches (there are files under version control, that might disappear on switching). Do `composer update` to trigger copying of the latest versions to .git/hooks/. Now check, that files in .git/hooks match devtools/git-pre-*. If that's OK, at least copying did work.

Next step. Please do the following from command line (not any GUI tool). I provide the expected results for reference.
1. Create a new PHP file test.php in the project directory, with `<? error` only in it
2. Run `Vendor/bin/phpcs --standard=devtools/fcs-rules.xml test.php`
Result like:
```
FILE: /var/www/html/foodcoopshop/test.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | [x] Short PHP opening tag used; expected "<?php" but
   |       |     found "<?"
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 287ms; Memory: 2.75Mb
```
There is no change to the file itself, just error messages.

3. Run `git add test.php` and `git commit -m "test"`.
Result like:
```
Checking PHP Lint...
PHP Parse error:  syntax error, unexpected end of file in /var/www/html/foodcoopshop/test.php on line 2
Errors parsing /var/www/html/foodcoopshop/test.php
Fix the error(s) before commit.
```
There is no change to the file itself, just error messages.

4. Edit test.php and replace content by:
```
<?   
$empty='';  
if($empty) die();  
```
There are trailing spaces at the end of all lines. Do not forget to switch off trailing space removal in editor.

5. Run `git add test.php` and `git commit -m "test"` (commit message can be anything).
Result like:
```
Checking PHP Lint...
No syntax errors detected in /var/www/html/foodcoopshop/test.php
auto remove trailing whitespace in test.php!
auto remove trailing whitespace in test.php!
auto remove trailing whitespace in test.php!
...
```
In addition test.php should now have no trailing spaces anymore. My editor warns me about the file being changed and suggests reloading.

6. Last test: run `git push`.
Result like:
```
Username for 'https://github.com': k-pd
Password for 'https://k-pd@github.com': 
Running Code Sniffer

FILE: /var/www/html/foodcoopshop/test.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 1 | ERROR | [x] Short PHP opening tag used; expected "<?php" but
   |       |     found "<?"
 3 | ERROR | [x] Expected 1 space after IF keyword; 0 found
 3 | ERROR | [x] Inline control structures are not allowed
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 123ms; Memory: 2.75Mb

Fix the error(s) and commit the changed files before push.
error: Fehler beim Versenden einiger Referenzen nach 'https://github.com/foodcoopshop/foodcoopshop.git'
```
Again, this doesn't change the file. There are only messages.

7. Undo the last commit by `git reset --hard HEAD~`.

If any of these steps doesn't provide the result expected, please try to copy&paste the result in a comment. As a last resort I have to move away from shell to PHP for doing the required steps...

**Comment by k-pd** [comment]
Maybe this is misunderstood: `PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY` means, if you run **phpbcf** instead of phpcs this problem can be fixed automatically. But I do not use this tool, because I do not know how to add another git commit to the running git push.

**Comment by k-pd** [comment]
Rewrote the commit hook to automatically apply coding standards to the commit. Focussed on portability, all commands and shell constructs are said to work the same on all versions of Linux/Windows. Hope this is true...

Will remove the push hook, or are there any new requirements like "must pass all tests before pushing"?

**Comment by mrothauer** [comment]
the hooks are only triggered if i use command line (not in egit plugin of eclipse - which i normally use)

but if i use the command line, it seems to work, except that renaming causes errors. despite the errors, a .bak file is created and the content is cleaned!

`$ git commit -m "test"
Checking PHP Lint...
No syntax errors detected in D:\htdocs\foodcoopshop.dev/AppControllerTestMario.php
warning: LF will be replaced by CRLF in AppControllerTestMario.php.
The file will have its original line endings in your working directory.
auto remove trailing whitespace in AppControllerTestMario.php!
mv: cannot move 'AppControllerTestMario.php' to 'AppControllerTestMario.php.save': Device or resource busy
mv: cannot move 'AppControllerTestMario.php.bak' to 'AppControllerTestMario.php': Device or resource busy
sed: can't read AppControllerTestMario.php.save: No such file or directory
rm: cannot remove 'AppControllerTestMario.php.save': No such file or directory
[feature/issue-41-enforce-coding-standards d5b7da5] test
 1 file changed, 1 insertion(+), 1 deletion(-)
`

**Comment by mrothauer** [comment]
it would be great, if the tests ran before pushing - but maybe later. running all tests still takes a while (around one minute) and the db settings still need to be changed to "test" - and rechanged after test. i would simplify that before integrate it in the pushing rule.

#54

**Comment by mrothauer** [comment]
maybe you find a way to safely undo all my test commits? rebase?

**Comment by k-pd** [comment]
Thanks for testing. Looking at Your output You didn't run the latest version. Maybe I have to change the hook setting script to overwrite existing hooks...

EGit is using JGit by default, which does not state anything about hooks like there is no support for them. You may switch to Git for Windows as mentioned on the [EGit User Guide Pages](http://wiki.eclipse.org/EGit/User_Guide#Pointing_out_the_System_wide_configuration).

I will do my very best to remove your test commits, I usally do `git reset HEAD~1` after each commit test. Don't know anything about removing pushed commits, yet.

**Comment by mrothauer** [comment]
finally i ran a fresh composer update after changing AND updating the branch... its working great! git hooks are still not working in eclipse, but in terminal its working really good!
only one thing left: all files should be corrected (psr-2 and whitespace cleaning and maybe more?) in one commit, so that future commits do not include already existing wrong formats and the code is readable.
by the way: the migration tool is working "like a charm"!

**Comment by mrothauer** [comment]
since windows 10 creators update, git hooks are triggered in eclipse!

**Pull request closed without merging**
