### PR TITLE
Prepare database for MySQL 5.7

### PR DESCRIPTION
**Pull request by k-pd**
#108 
An easy solution for missing INSERT values is adding zero-ish default values to all "NOT NULL" DB columns (which is the pre-5.7 behaviour).

As the strict default values now also require valid, non-zero date / time values, the DATETIME default is CURRENT_TIMESTAMP. For DATE columns I suggest "the day before the default was added" (CURRENT_* don't work for that type). Maybe its better to change DATE to DATETIME columns?

### CODE REVIEW

**Comment by k-pd** [comment]
I don't know why, but on my machine the tests are now aborted without any messages in EmailOrderReminderShellTest. There is no hint in any log (MySQL, PHP, Apache, FoodCoopShop). Hope to find something...

**Comment by k-pd** [comment]
Got Shell tests running, now working on
```SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and does not contain nonaggregated column &#039;foodcoopshop_db_test.CakePayment.date_add&#039; which is not functionally dependent on columns in GROUP BY clause; this not is not incompatible with sql_mode=only_full_group_by```
and similar. These appear, as some ORDER_BY clauses use values, that may not be reliably the same between 2 queries (e.g. GROUP_BY selects a random row and ORDER_BY sorts by a now possibly random value). The new default doesn't allow that anymore, but there are workarounds, e.g ANY_VALUE()

**Comment by k-pd** [comment]
@mrothauer "0000-00-00" is no longer a valid date literal. I found Your new holiday implementation is using this heavily. Is there a reason, why You choose "0000-00-00" over NULL? NULL would be perfectly fine as far as I can see. I can adjust the table definition now to allow NULL and instead of "holiday_from = '0000-00-00'" (or "holiday_to") use "holiday_from = NULL".

**Comment by k-pd** [comment]
@mrothauer To avoid "ORDER BY clause is not in GROUP BY" or similar errors now generated by default, I try to describe the cause. Imagine a table like this:
```
A  |  B  |  C
1  |  1  |  1
2  |  1  |  4
3  |  2  |  3
```
A query `SELECT * FROM table GROUP_BY B;` will result in:
```
A  |  B  |  C
1  |  1  |  1
3  |  2  |  3
```
or
```
A  |  B  |  C
2  |  1  |  4
3  |  2  |  3
```
depending on the sequence of rows found in the table file itself. B is perfectly grouped, but any value in a column other than B is seen by MySQL as "non-deteministic" (more or less random). To avoid unexpected results on a query, MySQL wants us to use "deterministic values" only in all clauses stated (WHERE, ORDER_BY etc.). So `GROUP_BY B ORDER_BY B` is OK to MySQL, `GROUP_BY B ORDER_BY C` is not.

If You cannot avoid using a non-deterministic value for a clause, MySQL has a special function ANY_VALUE() to tell it: "I know what I'm doing". So `GROUP_BY B ORDER_BY ANY_VALUE(C)` is OK.

**Comment by mrothauer** [comment]
holiday_mode: NULL instead of '0000-00-00' should be fine (and is probably the better solution)

**Comment by mrothauer** [comment]
have you finished? if so, please add the changed dump files (with the script you made). thx.

**Comment by k-pd** [comment]
It's not completely done, yet. Moving away from '0000-00-00' must be done for all DATE, DATETIME and TIMESTAMP columns. Hope to finish it until weekend.

**Comment by k-pd** [comment]
@mrothauer Please take a look at these failures. They started, when I adjusted the test DB data to be without import warnings (DATE and DATETIME from zero-ish value to '1000-01-01'). Any hint where to start searching?

**Comment by mrothauer** [comment]
i think that you did not update your test database with test-db-data.sql from develop before running bash Vendor/bin/db_dump_all
there were important configuration settings changed and that's why the tests failed.
workflow for dumping a migration into the dumps:

1) import clean-db-structure.sql to default config and test config
2) import clean-db-data.sql to default config
3) import test-db-data.sql to test config
4) run migration on both databases
5) change configurations FCS_DB_UPDATE and FCS_DB_VERSION to current migration on both databases
6) run bash Vendor/bin/db_dump_all
7) check in the changed dumps

this workflow could be improved by passing the migration number to the script (and the script takes care of the rest) => would be much less error prone

**Comment by mrothauer** [comment]
hmmm, to be clean, the migration script should change existing wrong date "defaults" like 0000-00-00  to null, shouldn't it?

**Comment by k-pd** [comment]
Actually I did exactly the same workflow, but before importing the DB data files I corrected all date values to be allowed ones. Now You turned them back into disallowed '0000-00-00'. And yes, now the test are run correctly, but illegal values are imported.

That importing can happen, because during import nearly all checks are disabled. I stopped trying to convert already stored illegal values because the tests didn't run anymore. I wanted to correct that, before doing a search and replace on stored dates in the migration file.

When looking at [Your commit](https://github.com/foodcoopshop/foodcoopshop/pull/109/commits/3fb65fda62a28c8e286905f99fe820db1eebd4bb) there is also an eMail address inserted. This caused my trouble. What ever happened to it in my file...

**Comment by k-pd** [comment]
@mrothauer Unit tests are now passing, I tested with some data to update correctly. Please clone some larger installations and apply the migration for a final test. There should not be any warning on execution.

**Pull request merged**
