### PR TITLE
travis adaptions for ubuntu trusty

### PR DESCRIPTION
**Pull request by mrothauer**
maybe you can help me, michael? the virtual host is working (see output in line 931 of travis log https://travis-ci.org/foodcoopshop/foodcoopshop/builds/256673980)

but when the host is called by the tests, there is a problem with the cache permissions.
SplFileInfo::openFile(/home/travis/build/foodcoopshop/foodcoopshop/tmp/cache/persistent/myapp_cake_core_method_cache): failed to open stream: Permission denied

### CODE REVIEW

**Comment by k-pd** [comment]
Scaninng the Travis log.

In line 416ff. Travis clones foodcoopshop. It then changes into the foodcoopshop path (pwd = `/home/travis/build/foodcoopshop/foodcoopshop/`). In line 527ff. you clone foodcoopshop again, into `/home/travis/build/foodcoopshop/foodcoopshop/foodcoopshop/` (this is also done wrong, it results in develop/HEAD). In .travis.yml You continue to use the Travis-cloned worktree, which is fine (as far as I can see). I removed Your cloning.

But to Your access denied problem: I also have this here. I am logged in as user "michael", Apache is running as user "www-data". When creating temp files, Apache does not set them to 0666 but 0640, which is the default behaviour in Linux. Now running a console command as user "michael" results in "access denied". Its also the other way around: running a console command as user "michael" creates temp files inaccessible to "www-data". Solution: run console commands as user "www-data", too: `sudo -u www-data -- ./Console/cake test app AllFoodCoopShopTests --stderr`. I changed the command to this.

**Comment by k-pd** [comment]
@mrothauer Why is Travis-CI not running my latest changed .travis.yml? It still runs my first change.

**Comment by k-pd** [comment]
@mrothauer OK, the push build did my latest changes, but there still is another problem. www-data doesn't have the required access rights to run PHP from console. Do You have something like a console access to Travis build environment? It then would be easier to test changing the PHP-FPM user to the travis build user and such.

**Comment by mrothauer** [comment]
sorry, afaik there's no console access to travis. maybe this line
sudo ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
causes the problem? it was not run with sudo on ubuntu precise.

**Comment by k-pd** [comment]
You must start php-fpm as root, it then uses sudo and the user You set in php-fpm.conf for running. I'll do my very best to get it running...

**Comment by mrothauer** [comment]
great great great!

i removed the unnecessary chown / chmod.

i also tried to add php5.5, 5.6 and 7.0, but the script stopped:
[24-Jul-2017 13:19:21] ERROR: [pool www] cannot get gid for group 'nobody'
[24-Jul-2017 13:19:21] ERROR: FPM initialization failed
The command "sudo ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm" failed and exited with 70 during .
see
https://travis-ci.org/foodcoopshop/foodcoopshop/jobs/256880486

would it be ok to just run the tests just php 7.1?

if so, can you please "squash and merge" the pull request so that the produced commit will be yours? thanks a lot for helping me out!

**Pull request merged**
