### PR TITLE
feature/issue 27 admin mobile

### PR DESCRIPTION
**Pull request by mrothauer**
the admin area was not responsive at all. with these changes mobile working with the admin is easier, although not perfect...

### CODE REVIEW

**Comment by k-pd** [comment]
Cannot review mobile stuff. No mobile devices here. Or is mobile detection based on screen size? Haven't digged into it, just saw something like isMobile() in a template file...

**Comment by mrothauer** [comment]
mobile stuff is based on the user agent, you could test it with google chrome or firefox
https://developers.google.com/web/tools/chrome-devtools/device-mode/

a quick view at the changes also helps me, two eyes see more than one :-)

**Comment by k-pd** [comment]
Changing the user agent can be done. Are there different mobile types? Worked with "iphone" once.

**Comment by mrothauer** [comment]
different mobile types are not considered. tablets get the desktop version, this would be a new issue.

**Comment by k-pd** [comment]
Took a short look at it. These came up quickly:

1. On frontpages, the info box is displayed along with the new menu and info icon. This is with the cart also.
2. In the menu, there are empty items ("Kategorien" and "Seiten" for my setup).
3. Going to Admin leaves me with an empty screen (no useful icons or links) I have to open the menu first. Would prefer having the menu directly opened.
4. Activity Log: On small screen sizes the filter and list are just truncated, not rearranged / resized.
5. Not sure about: font size might be too small for safe touching at least on modern smartphone displays
6. When scrolling through long lists I would prefer having the filter / table headers sticking at the top.
7. The Logout window is stretched to 100% screen width, even in landscape view (maybe limit to 500px?)

**Comment by mrothauer** [comment]
thanks for the feedback!

1) i did not touch the mobile version for the frontend (and i don't quite understand what you mean)
2) that's ok. i just did not cover the case of no pages and no categories (every working foodcoop will have at least one page and category)
3) good point - i will change that
4) sorry, i don't get it. could you provide a screenshot?
5) hmmm, i'll check it again
6) good point
7) ok - i'll change that

**Comment by k-pd** [comment]
To 1: Take a look at the screenshots. Last one is the expected behaviour.
frontpage
frontpage2
frontpage3

**Comment by k-pd** [comment]
To 3: Doesn't work on my setup. Menu still closed on opening /admin

**Comment by k-pd** [comment]
To 4: Filters and list cut off, not rearranged. See Screenshot.
activitylog

**Comment by k-pd** [comment]
To 7: Not working on my setup, see screenshot.
logout

**Comment by k-pd** [comment]
I messed up with local versions, sorry. 4. and 7. are working well.

To 6: Is working partially. Opening the menu, then scrolling the list -> filters move away.

**Comment by k-pd** [comment]
To 4: The list is still cut off, the filterbar is now rearranging.

**Comment by k-pd** [comment]
To 5: In portrait mode the menu items are separated and indented, in landscape mode they aren't. This is where I think they are hard to touch on a smartphone. See screenshots.
menu
menu2

**Pull request merged**
